<ul class="nav navbar-nav text-uppercase">
	<li class="dropdown dropdown-fw open selected"><a
		class="text-uppercase" href="/index"> <i class="icon-home"></i>
			Tableau de bord
	</a>
</li>
	<li id="menu_admin_membres" class="dropdown more-dropdown"><a class="text-uppercase"
		href="/members" data-close-others="true"> Membres </a>
		<ul class="dropdown-menu">
			<li><a href="/members">Liste des membres</a></li>
			<li><a href="/cotisations">Cotisations</a></li>
		</ul></li>
	
	<li id="menu_admin_charges" class="dropdown dropdown-fw"><a class="text-uppercase"
		href="/charges"> Charges </a>
	</li>
	<li id="menu_admin_history" class="dropdown dropdown-fw"><a class="text-uppercase"
		href="/history"> Historique </a>
	</li>	
</ul>