<div class="row">
	<div class="col-md-12" id="BLOCK_MSG_FORM_CHARGE"></div>
</div>
<form id="FORM_CHARGE">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"
				aria-hidden="true"></button>
			<h4 class="modal-title">
				<i class="fa fa-edit"></i> <?=($charge==null)?'Ajout':'Edition';?> charge
			</h4>
		</div>
		<div class="modal-body form">
			<div class="form-body">

				<input type="hidden" name="CHARGE_ID"
					value="<?=($charge==null)?0:$charge->getId();?>">

				<div class="form-group">
					<label>Type de charge : </label> <select
						class="form-control input-sm" name="SELECT_TYPE_CHARGE_1"
						id="SELECT_TYPE_CHARGE_1">
					</select>
				</div>

				<div class="form-group">
					<label>Date : </label> <input id="date_picker_charge"
						class="form-control input-sm date-picker" size="16"
						name="CHARGE_DATE" type="text" value="<?=($charge==null)?'':$charge->getDatecharge()->format ( 'd-m-Y' );?>" />
				</div>

				<div class="form-group">
					<label>Libellé : </label> <input type="text" name="CHARGE_LABEL"
						class="form-control input-sm" value="<?=($charge==null)?'':$charge->getLabel();?>">
				</div>

				<div class="form-group">
					<label>Montant (dh) : </label> <input type="text"
						name="CHARGE_MONTANT" class="form-control input-sm" value="<?=($charge==null)?'':$charge->getMontant();?>">
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<button type="button" id="BTN_CLOSE_MODAL_CHARGE"
				class="btn default btn-sm" data-dismiss="modal">
				<i class="fa fa-times"></i> Fermer
			</button>
			<button type="submit" id="BTN_SUBMIT_FORM_CHARGE"
				class="btn blue btn-sm">
				<i class="fa fa-save"></i> Valider
			</button>
		</div>
	</div>
</form>
<script type="text/javascript"
	src="ressources_myhd/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
<script type="text/javascript">
$('.date-picker').datepicker({
    orientation: "left",
    format: 'dd-mm-yyyy',
    autoclose: true,
});

//VALIDATION FORM
var form_charge = $('#FORM_CHARGE');
var error3 = $('.alert-danger', form_charge);
var success3 = $('.alert-success', form_charge);
	
form_charge.validate({
    errorElement: 'span', //default input error message container
    errorClass: 'help-block help-block-error', // default input error message class
    focusInvalid: false, // do not focus the last invalid input
    ignore: "",  // validate all fields including form hidden input
    messages: {
    },
    rules: {
    	CHARGE_DATE:{
    		required: true,
        },
        CHARGE_LABEL:{
    		required: true,
        },
        CHARGE_MONTANT:{
            required:true,
        	number: true,
        },
    },

    invalidHandler: function (event, validator) { //display error alert on form submit              
        success3.hide();
        error3.show();
        Metronic.scrollTo(error3, -200);
    },

    highlight: function (element) { // hightlight error inputs
        $(element)
            .closest('.form-group').addClass('has-error'); // set error class to the control group
    },

    unhighlight: function (element) { // revert the change done by hightlight
        $(element)
            .closest('.form-group').removeClass('has-error'); // set error class to the control group
    },

    success: function (label) {
        label
            .closest('.form-group').removeClass('has-error'); // set success class to the control group
    },

    submitHandler: function (form) {
        error3.hide();
        //return false;
       $(form).attr('action', "/charge_processing");
			$('#BTN_SUBMIT_FORM_CHARGE,#BTN_CLOSE_MODAL_CHARGE').attr("disabled", false);
			$('#BLOCK_MSG_FORM_CHARGE').html(loader_modal_html);
			var formData = $(form).serializeArray();
			$.ajax({			
		        url: $(form).attr("action"),          
		        type : "POST",
		        dataType:'json',
		        data:  formData,
		        success : function(data) {
		        	if(data.success==true){
		        		$('#BTN_SUBMIT_FORM_CHARGE,#BTN_CLOSE_MODAL_CHARGE').attr("disabled", false);
		        		reload_datatable_charges();
		        		$('#BLOCK_MSG_FORM_CHARGE').html('<div class="alert alert-success">'+data.message+'</div>');
	        			toastr.success(data.message, 'Succès');
	        			$('#BTN_CLOSE_MODAL_CHARGE').click();
		        	}else{
		        		toastr.error(data.message, 'Erreur');
		        		$('#BTN_SUBMIT_FORM_CHARGE,#BTN_CLOSE_MODAL_CHARGE').attr("disabled", false);
		        		$('#BLOCK_MSG_FORM_CHARGE').html('<div class="alert alert-danger">'+data.message+'</div>');
		        	}
		         },
		        error:function(err){
		        	toastr.error('Erreur...', 'Erreur');
		        	$('#BTN_SUBMIT_FORM_CHARGE,#BTN_CLOSE_MODAL_CHARGE').attr("disabled", false);
		        	$('#BLOCK_MSG_FORM_CHARGE').html('<div class="alert alert-danger">Erreur ...</div>');
			    }
				});     			
			return false;
        
    }
});

getSelectTypesCharge();
function getSelectTypesCharge(){
		var SELECT_TYPE_CHARGE = $('#SELECT_TYPE_CHARGE_1');
		$.ajax({
	        url: '/get_select_type_charge',
	        dataType: 'json',
	        success: function(json) {
	            $.each(json, function(index, value) {
	            	var selected='';
	            	<?php if ($charge!=null):?>
            			var codeCharge="<?=$charge->getType();?>";
						if('"'+codeCharge+'"'==index){
	            			selected='selected="selected"';
						}
            		<?php endif;?>
	            	SELECT_TYPE_CHARGE.append('<option value='+ index +' '+selected+' >'+ value +'</option>');
	            });
	        }
	    });
	}

</script>