<?php
$title = 'HISTORIQUES | SYNDIC ALMANAR C 126';
$this->headTitle ( $title );
?>
<?php

echo $this->headLink ()->prependStylesheet ( $this->basePath ( 'ressources_myhd/assets/global/plugins/bootstrap-toastr/toastr.min.css' ) )
->prependStylesheet ( $this->basePath ( 'ressources_myhd/assets/global/plugins/select2/select2.css' ) )
->prependStylesheet ( $this->basePath ( 'ressources_myhd/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css' ) );
?>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-ehcg">
			<div class="panel-heading">
				<h3 class="panel-title">
					<i style="color: #fdc300;" class="fa fa-chevron-right"></i> Historiques
				</h3>
			</div>
			<div class="panel-body">



				<div class="row">
					<div class="col-md-12">


						<table class="table table-striped table-bordered table-hover"
							id="table_history">
							<thead>
								<tr>
									<th class="table-checkbox"><input type="checkbox"
										class="group-checkable"
										data-set="#table_history .checkboxes" /></th>
									<th>N°</th>
									<th>Date</th>
									<th>Historique</th>
								</tr>
							</thead>
							<tbody>
							</tbody>
						</table>
					</div>
				</div>


			</div>
		</div>
	</div>
</div>


<!-- Modal loading -->
<div class="modal fade bs-modal-sm" id="modal_loading" tabindex="-1"
	data-backdrop="static" role="basic" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div id="modal_loading_body"
			class="modal-content loading-message loading-message-boxed"></div>
	</div>
</div>
<!--  End loading -->

<!--  MODAL COTISATION -->
<div class="modal fade bs-modal-lg" id="modal_charges" tabindex="-1"
	role="dialog" aria-hidden="true">
	<div class="modal-dialog" id="modal_content_charges"></div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->


<?php
echo $this->headScript ()
->prependFile ( $this->basePath ( 'ressources_myhd/assets/global/plugins/bootstrap-toastr/toastr.min.js' ) )
->prependFile ( $this->basePath ( 'ressources_myhd/assets/global/plugins/bootbox/bootbox.min.js' ) )
->prependFile ( $this->basePath ( 'ressources_myhd/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js' ) )
->prependFile ( $this->basePath ( 'ressources_myhd/assets/global/plugins/datatables/media/js/jquery.dataTables.min.js' ) )
->prependFile ( $this->basePath ( 'ressources_myhd/assets/global/plugins/select2/select2.min.js' ) )
->prependFile ( $this->basePath ( 'js/localization_js_validation/messages_fr.js' ) )
->prependFile ( $this->basePath ( 'ressources_myhd/assets/global/plugins/jquery-validation/js/jquery.validate.min.js' ) );
?>

<script type="text/javascript">
	$('li').removeClass('open');
	$('#menu_admin_history').addClass('active-wtp');

	var loader_html = "<div class='loading-message loading-message-boxed'><center><i style='font-size:20px;color:#444868' class='fa fa-spinner fa-spin'></i> Traitement en cours ...veuillez patientez</center></div>";
	var loader_modal_html = "<center style='color:#444868;'><i style='font-size:20px;' class='fa fa-spinner fa-spin'></i> Traitement en cours ...</center>";
	
	var table = $('#table_history');

    // begin first table
    table.dataTable({

        // Internationalisation. For more info refer to http://datatables.net/manual/i18n
        "language": {
        	"processing":"Traitement en cours...",
            "aria": {
                "sortAscending": ": activer pour trier la colonne par ordre croissant",
                "sortDescending": ": activer pour trier la colonne par ordre d&eacute;croissant"
            },
            "emptyTable": "Aucune donn&eacute;e disponible dans le tableau",
            "info": "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
            "infoEmpty": "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
            "infoFiltered": "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
            "infoPostFix":    "",
            "loadingRecords": "<i class='fa fa-spinner fa-spin'></i> Chargement en cours...",
            "lengthMenu": "Afficher _MENU_ &eacute;l&eacute;ments",
            "search": "Filtrer&nbsp;:",
            "zeroRecords": "Aucun &eacute;l&eacute;ment &agrave; afficher",
            "paginate": {
                "previous":"Pr&eacute;c&eacute;dent",
                "next": "Suivant",
                "last": "Dernier",
                "first": "Premier"
            }
		},
		"ajax": {
			    "url": "/source_datatable_history", // ajax source
		},	
		 "processing": true,
		 "ordering":false,
        "bStateSave": false, // save datatable state(pagination, sort, etc) in cookie.
        "lengthMenu": [
            [5, 15, 20, -1],
            [5, 15, 20, "All"] // change per page values here
        ],
        // set the initial value
        "pageLength": 5,            
        "pagingType": "bootstrap_full_number",
        "columnDefs": [{  // set default column settings
            'orderable': false,
            'targets': [0]
        }, {
            "searchable": false,
            "targets": [0]
        }],
        "drawCallback": function( settings ) {
        	$('[data-toggle="tooltip"]').tooltip();       	
    	},
    	"fnInitComplete" : function(settings, json){ 
        	$('[data-toggle="tooltip"]').tooltip();        
    	}
    });

    var tableWrapper = jQuery('#table_history_wrapper');

    table.find('.group-checkable').change(function () {
        var set = jQuery(this).attr("data-set");
        var checked = jQuery(this).is(":checked");
        jQuery(set).each(function () {
            if (checked) {
                $(this).attr("checked", true);
                $(this).parents('tr').addClass("active");
            } else {
                $(this).attr("checked", false);
                $(this).parents('tr').removeClass("active");
            }
        });
        jQuery.uniform.update(set);
    });

    table.on('change', 'tbody tr .checkboxes', function () {
        $(this).parents('tr').toggleClass("active");
    });

    tableWrapper.find('.dataTables_length select').addClass("form-control input-xsmall input-inline"); // modify table per page dropdown


    function reload_datatable_history(){
  	  table.api().ajax.url( "/source_datatable_history").load();
  	}
 
</script>
